### ISSUE TITLE
Re-evaluate Vector Maps

### ISSUE THREAD

**Issue by khdlr** [open-pv/website#279]
basemap.de does have vector maps in pbf format. Can we make use of them to get rid of the current pixely raster maps?

* Changing the initial search screen should be easy as it's based on MapLibre
* The simulation screen will be a bit more difficult, but there are projects such as https://areknawo.github.io/ThreeMap

**Comment by wiesehahn** [comment]
I would definitely change the map to using vector tiles, the basemap.de raster version simply makes no sense. maplibre is designed for vector tiles and the data is also vector based. Would be much more crisp.

Additionally, you could use the official DGM5 data to also render terrain (instead of relying on external data by sonny). 

Additionally, you could add the LOD2 Builings directly. 

See example https://basemap.de/beta-lod2-gelaende/

**Comment by khdlr** [comment]
Will change the initial map screen to use vector maps and look into how it could be done for the 3D simulation view.

As for the DGM5 and LOD2 data products from basemap.de, we would love to use them both, but sadly they are under a quite restrictive license (https://basemap.de/data/produkte/3d/lizenzen/lizenz_basemapde_3D-Beta.pdf). This only allows use for testing purposes and prohibits download or use of the data in production. We're regularly monitoring basemap.de for updates to the licensing. Our data structures are kept largely compatible with their data products, so we could easily switch when they become openly available.

**Comment by FlorianK13** [comment]
@khdlr This issue can be closed, right?

**Comment by khdlr** [comment]
Pretty much, I would consider part 2 out of scope for now
